name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16' 

    - name: Build and Deploy
      run: |
        mkdir deploy
        cp index.html deploy/index.html

    - name: Debug - List files
      run: ls -la deploy

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.2
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: deploy

    - name: Debug - Check Git version
      run: git --version

    - name: Debug - Show Git config
      run: git config --list
