name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.11.0
      with:
        access_token: ${{ secrets.PAT_TOKEN }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}

    - name: Add DigitalOcean server to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan 64.227.65.168 >> ~/.ssh/known_hosts

    - name: Copy files to DigitalOcean
      run: |
        rsync -avz --delete ./ root@64.227.65.168:/var/www/html/

    - name: Execute deployment script
      env:
        SSHPASS: ${{ secrets.DIGITALOCEAN_PASSWORD }}
      run: |
        sshpass -e ssh root@64.227.65.168 'bash -s' < ./install-n-deploy.sh
