name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main
      - branch1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
         ssh-private-key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}

    - name: Add DigitalOcean server to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan 64.227.65.168 >> ~/.ssh/known_hosts

    - name: Deploy based on branch
      run: |
        if [ "${{ github.ref }}" == "refs/heads/main" ]; then
          rsync -avz --delete ./ root@64.227.65.168:/var/www/learning.moonhive-server.in.net/
          sshpass -e ssh root@64.227.65.168 'bash -s' < ./install-n-deploy.sh
        elif [ "${{ github.ref }}" == "refs/heads/branch1" ]; then
          rsync -avz --delete ./ root@64.227.65.168:/var/www/learning2.moonhive-server.in.net/
          sshpass -e ssh root@64.227.65.168 'bash -s' < ./install-n-deploy.sh
        else
          echo "This action runs only on 'main' or 'branch1' branches."
        fi
      env:
        SSHPASS: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
